# docker-compose.yml

services:
  # Aplikacja backendowa w python (Flask)
  projekt-gry:
    command: sleep infinity
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    # ports:
      # - "5000:5000"  # Mapowanie portu kontenera (5000) na ten sam port w komputerze (5000)
    volumes:
      - ..:/workspaces:cached # Mapowanie kodu źrodłowego, aby zmiany były widoczne na komputerze
    environment:
      - MONGO_URI=mongodb://mongo:mongo@mongo:27017 # Przekazanie adresu URL bazy dancyh
      - FLASK_APP=app.py
      - FLASK_ENV=development # Uruchomienie Flask w trybie deweloperskim
  # Baza danych MongoDB
  mongo:
    image: mongo:latest # Oficjalnyy obraz MongoDB
    ports:
      - "27017:27017" # Mapowanie portu MongoDB
    volumes:
      - mongo-data:/data/db # Zapisanie danych bazy danych, aby nie znikneły po restarcie komputera
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo # Dane potrzebne do połączenia z bazą danych
      MONGO_INITDB_ROOT_PASSWORD: mongo

volumes:
  mongo-data:
  